import { RpsGameController } from './controller';
import type { RpsActionController, RpsScheduler, RpsState, RpsVisionRuntime } from './types';
import type { VisionLandmarkResult, VisionRuntimeSnapshot } from '../../shared/vision-runtime';

class FakeScheduler implements RpsScheduler { private id = 0; private tasks = new Map<number, () => void>(); setTimeout(callback: () => void, _delayMs: number): number { const id = ++this.id; this.tasks.set(id, callback); return id; } clearTimeout(id: number): void { this.tasks.delete(id); } runNext(): void { const entry = this.tasks.entries().next().value as [number, () => void] | undefined; if (entry) { this.tasks.delete(entry[0]); entry[1](); } } }
class FakeRuntime implements RpsVisionRuntime { private snapshotValue: VisionRuntimeSnapshot = { state: 'idle', owner: null, cameraDeviceId: null, model: 'unloaded', frameSequence: 0, fps: null, droppedFrames: 0, inflight: 0, lastError: null }; private runtimeListeners = new Set<(snapshot: VisionRuntimeSnapshot) => void>(); private resultListeners = new Set<(result: VisionLandmarkResult) => void>(); starts = 0; stops = 0; start = async (_video: HTMLVideoElement, source: 'rps') => { this.starts += 1; this.snapshotValue = { ...this.snapshotValue, state: 'running', owner: source, model: 'ready' }; this.runtimeListeners.forEach(listener => listener(this.snapshotValue)); }; stop = async () => { this.stops += 1; this.snapshotValue = { ...this.snapshotValue, state: 'idle', owner: null, model: 'unloaded' }; this.runtimeListeners.forEach(listener => listener(this.snapshotValue)); }; subscribe = (listener: (snapshot: VisionRuntimeSnapshot) => void) => { this.runtimeListeners.add(listener); listener(this.snapshotValue); return () => this.runtimeListeners.delete(listener); }; onResult = (listener: (result: VisionLandmarkResult) => void) => { this.resultListeners.add(listener); return () => this.resultListeners.delete(listener); }; snapshot = () => this.snapshotValue; emit = (result: VisionLandmarkResult) => this.resultListeners.forEach(listener => listener(result)); }
const capabilities = (model: 'O6' | 'L7') => ({ model, supportedOperations: model === 'O6' ? ['setPosition'] : [] } as never);
const result = (): VisionLandmarkResult => ({ source: 'rps', hands: [], monotonicTimeMs: 1, frameSequence: 1, fps: 30, droppedFrames: 0, inflight: 0 });
const fakeVideo = {} as HTMLVideoElement;

describe('RPS lifecycle and deterministic countdown', () => {
  it('uses one injected runtime, fake clock, and releases on unmount', async () => { const runtime = new FakeRuntime(); const scheduler = new FakeScheduler(); const controller = new RpsGameController({ runtime, capabilities: capabilities('L7'), scheduler, random: () => 0 }); const states: RpsState[] = []; controller.subscribe(state => states.push(state)); await controller.attach(fakeVideo); await controller.startCamera(); expect(runtime.starts).toBe(1); expect(controller.beginRound()).toBe(true); expect(controller.snapshot().countdown).toBe(3); scheduler.runNext(); expect(controller.snapshot().countdown).toBe(2); scheduler.runNext(); expect(controller.snapshot().countdown).toBe(1); scheduler.runNext(); expect(controller.snapshot().phase).toBe('capture'); runtime.emit(result()); expect(controller.snapshot().phase).toBe('capture'); await controller.dispose(); expect(runtime.starts).toBe(1); expect(runtime.stops).toBe(1); expect(states.some(state => state.phase === 'countdown')).toBe(true); });
  it('does not dispatch without O6 authorization and cancels when locked', async () => { const runtime = new FakeRuntime(); const scheduler = new FakeScheduler(); const controllerCalls = { authorize: 0, dispatch: 0, cancel: 0 }; const action: RpsActionController = { authorize: async () => { controllerCalls.authorize += 1; return true; }, dispatch: async () => { controllerCalls.dispatch += 1; return { status: 'executed' }; }, cancel: async () => { controllerCalls.cancel += 1; } }; const controller = new RpsGameController({ runtime, capabilities: capabilities('O6'), actionController: action, scheduler }); await controller.attach(fakeVideo); await controller.startCamera(); expect(controller.beginRound()).toBe(false); await controller.authorizeHardware(); expect(controllerCalls.authorize).toBe(1); expect(controller.beginRound()).toBe(true); controller.lock(); expect(controllerCalls.dispatch).toBe(0); expect(controllerCalls.cancel).toBe(1); });
});
